# Service Name
spring.application.name=user-service
server.port=8081

# Database Configuration (Postgres for Mac M2)
# Homebrew installation
spring.datasource.url=jdbc:postgresql://localhost:5432/db_user_service
spring.datasource.username=shobhitsamaria
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/